/* ---------- DATA (tout le contenu du PDF) ---------- */
const MV = [
 {id:"hum", n:"L'Humanisme", p:"XVIe siècle",
  c:[["Fondé sur la redécouverte des textes antiques et de la Bible",["pl"]],
     ["Essai de revenir aux textes originaux",["pl"]],
     ["Caractérisé par la foi dans l'humain / élan vers le savoir (scientifique)",["lum"]]],
  w:[["Les Essais",1580,"Montaigne"],["Pantagruel",1532,"Rabelais"],["Gargantua",1534,"Rabelais"]],
  q:[["Mieux vaut une tête bien faite qu'une tête bien pleine.","Montaigne"]],
  x:[{q:"« Mieux vaut une tête bien faite qu'une tête bien pleine » (Montaigne) : quelle idée ?",a:"Remise en question de l'éducation",o:["Critique de la religion","Éloge de la mémoire","Défense de la langue française"]},
     {t:1,q:"Compléter : « Mieux vaut une tête bien ___ qu'une tête bien ___ » (iki kelimeyi yaz)",a:"faite / pleine",o:["pleine / faite","remplie / vide","pensante / savante"]}]},
 {id:"pl", n:"La Pléiade", p:"XVIe siècle",
  c:[["Découle de l'Humanisme et de la redécouverte des textes antiques",[]],
     ["Un groupe de poètes soucieux de prouver que la poésie peut égaler les textes de l'Antiquité",["cla"]]],
  w:[["Les Amours",1560,"Ronsard"],["Défense et illustration de la langue française",1549,"Du Bellay"],["Les Regrets",1558,"Du Bellay"]],
  q:[], x:[]},
 {id:"bar", n:"Le Baroque", p:"Fin XVIe – moitié XVIIe siècle",
  c:[["Un art chargé et tourmenté (architecture / sculpture / peinture)",[]],
     ["Deux branches principales : le noir et le blanc",[]],
     ["En littérature, des écrivains exprimant une sensibilité inquiète face à un monde instable et en mouvement",[]],
     ["Prise de conscience de l'absurdité de la condition humaine",["abs"]],
     ["Utilisation de mises en abyme et de rebondissements",[]]],
  w:[["L'Illusion comique",1635,"Corneille"],["Stances sur la mort",1595,"Jean de Sponde"]],
  q:[],
  x:[{q:"Baroque NOIR = ?",a:"Tensions / angoisses",o:["Ornemental / exubérant","Équilibre / mesure","Rêve / inconscient"]},
     {q:"Baroque BLANC = ?",a:"Ornemental / exubérant",o:["Tensions / angoisses","Neutre / impersonnel","Mystère / nuance"]},
     {q:"Le Baroque est un art chargé et tourmenté dans quels domaines ?",a:"Architecture / sculpture / peinture",o:["Musique / danse / théâtre","Roman / poésie / essai","Philosophie / science / politique"]}]},
 {id:"cla", n:"Le Classicisme", p:"Seconde moitié du XVIIe siècle",
  c:[["Basé sur le modèle antique",["hum","pl"]],
     ["Recherche l'équilibre / la mesure",[]],
     ["Représentation de l'âme humaine de façon universelle",[]],
     ["Codification stricte, notamment au théâtre",[]],
     ["Règle des 3 unités",[]],["Règle de vraisemblance",[]],["Règle de bienséance",[]]],
  w:[["Horace",1640,"Corneille"],["Tartuffe",1669,"Molière"],["Phèdre",1673,"Racine"],["Les Fables",1668,"La Fontaine"]],
  q:[],
  x:[{q:"Règle des 3 unités = ?",a:"1 jour / 1 action / 1 lieu",o:["1 acte / 1 héros / 1 lieu","1 jour / 1 personnage / 1 décor","1 lieu / 1 thème / 1 siècle"]},
     {q:"Règle de VRAISEMBLANCE = ?",a:"Ça semble réel / plausible",o:["Respect des conventions / ne pas choquer","1 jour / 1 action / 1 lieu","Exalter le « moi »"]},
     {q:"Règle de BIENSÉANCE = ?",a:"Respect des conventions / ne pas choquer",o:["Ça semble réel / plausible","1 jour / 1 action / 1 lieu","Représenter la réalité de façon neutre"]},
     {t:1,al:["esope","fables d esope"],q:"Les Fables de La Fontaine font référence aux Fables de qui ?",a:"Ésope",o:["Les Métamorphoses d'Ovide","L'Iliade d'Homère","La République de Platon"]}]},
 {id:"lum", n:"Les Lumières", p:"XVIIIe siècle",
  c:[["Un groupe d'intellectuels, d'acteurs, de poètes, de philosophes : des personnes engagées",[]],
     ["Idée que l'homme peut améliorer sa condition par le progrès et la raison",[]],
     ["Esprit critique pour lutter contre l'obscurantisme et les préjugés",[]],
     ["Pensée nouvelle remettant en cause les mœurs et la suprématie bourgeoise",[]]],
  w:[["L'Encyclopédie",1751,"D'Alembert et Diderot"],["Du contrat social",1762,"Rousseau"],["Lettres persanes",1721,"Montesquieu"],
     ["Le Mariage de Figaro",1778,"Beaumarchais"],["Traité sur la tolérance",1763,"Voltaire"],["Candide",1759,"Voltaire"]],
  q:[["Une véritable attitude intellectuelle, celle d'oser penser par soi-même.","Kant"]],
  x:[{t:1,al:["revolution francaise","1789 revolution francaise","la revolution"],q:"Les Lumières mènent à quel événement ? (yıl veya olay)",a:"1789",o:["1848, la Deuxième République","1685, la révocation de l'édit de Nantes","1914, la Première Guerre mondiale"]},
     {t:1,q:"Compléter (Kant) : « Une véritable attitude intellectuelle, celle d'oser ___ »",a:"penser par soi-même",o:["douter de tout","rêver sans raison","critiquer le roi"]}]},
 {id:"rom", n:"Le Romantisme", p:"Après la Révolution – 1re moitié du XIXe siècle",
  c:[["Volonté d'exalter le « moi » et de rompre avec l'esthétique classique",[]],
     ["Exaltation du « moi » lyrique = utilisation du « je »",[]],
     ["Idée de la liberté dans l'art",[]],
     ["Opposition au classicisme (représentation universelle de l'âme, règles strictes)",[]],
     ["Refus du rationalisme des Lumières, expression de la sensibilité",[]],
     ["Idée du « mal du siècle » : malaise et insatisfaction dans tous les domaines",[]],
     ["Le héros est soumis à une vague de passion, à une mélancolie sans cause et sans remède",[]]],
  w:[["René",1802,"Chateaubriand"],["Hernani",1830,"Victor Hugo"],["Les Contemplations",1856,"Victor Hugo"],["Lorenzaccio",1834,"Musset"]],
  q:[["On habite avec un cœur plein un monde vide.","Chateaubriand"]],
  x:[{t:1,q:"Compléter (Chateaubriand) : « On habite avec un cœur plein un monde ___ »",a:"vide",o:["froid","perdu","immense"]},
     {q:"Le « mal du siècle » est lié à quoi ?",a:"L'expression de l'individu",o:["L'hérédité et le milieu","La règle des 3 unités","Les théories freudiennes"]}]},
 {id:"rea", n:"Le Réalisme", p:"XIXe siècle",
  c:[["Représenter la réalité de son temps sous tous ses aspects, de la façon la plus neutre et impersonnelle possible",["nat"]]],
  w:[["Le Rouge et le Noir",1830,"Stendhal"],["Le Père Goriot",1835,"Balzac"],["Madame Bovary",1856,"Flaubert"]],
  q:[],
  x:[{t:1,q:"Qui a écrit « Le Réalisme » (1857) ?",a:"Champfleury",o:["Flaubert","Zola","Balzac"]},
     {t:1,q:"En quelle année Champfleury écrit-il « Le Réalisme » ?",a:"1857",o:["1830","1848","1864"]},
     {t:1,q:"Les 2 grands initiateurs du Réalisme ? (X et Y)",a:"Stendhal et Balzac",o:["Flaubert et Zola","Hugo et Musset","Zola et Goncourt"]},
     {t:1,q:"La Comédie humaine (Balzac) compte combien de textes ?",a:"93",o:["20","42","150"]},
     {q:"La Comédie humaine, c'est quoi ?",a:"Un portrait exhaustif de la société de son époque",o:["L'histoire d'une famille sur 5 générations","Un recueil de poèmes lyriques","Une pièce en 5 actes"]},
     {q:"Particularité du Père Goriot dans La Comédie humaine ?",a:"On y retrouve des personnages déjà présents dans d'autres romans",o:["C'est le premier roman sur le peuple","Il respecte la règle des 3 unités","Il est écrit en vers"]},
     {q:"Flaubert et l'étiquette « réaliste » ?",a:"Il la refuse absolument",o:["Il l'invente","Il l'accepte fièrement","Il la donne à Zola"]}]},
 {id:"nat", n:"Le Naturalisme", p:"XIXe siècle",
  c:[["S'appuie sur les sciences naturelles et l'enquête de terrain",[]],
     ["Analyse les effets de l'hérédité et du milieu sur les êtres",[]],
     ["Étudie l'influence du milieu social sur la descendance et l'évolution des générations",[]]],
  w:[["Les Rougon-Macquart",1886,"Zola"],["Germinie Lacerteux",1864,"Edmond de Goncourt"]],
  q:[["C'est une œuvre de vérité, le premier roman sur le peuple, qui ne mente pas, et qui ait l'odeur du peuple.","Zola"]],
  x:[]},
 {id:"sym", n:"Le Symbolisme", p:"Fin du XIXe siècle",
  c:[["Envisage le monde dans son mystère",[]],
     ["S'éloigne du réel pour se tourner vers le rêve et l'intériorité",["sur"]],
     ["Recherche de la nuance",[]],
     ["Représenter les liens entre les éléments de la nature en dévoilant les énigmes du monde au moyen de symboles",[]],
     ["Tente de libérer la poésie des règles traditionnelles",[]]],
  w:[["Les Fleurs du mal",1857,"Baudelaire"],["Poèmes saturniens",1866,"Verlaine"],["Poésies",1887,"Mallarmé"],["Illuminations",1886,"Rimbaud"]],
  q:[], x:[]},
 {id:"sur", n:"Le Surréalisme", p:"Début du XXe siècle",
  c:[["Impact des théories freudiennes et des thèses marxistes",[]],
     ["Explore la surréalité en libérant l'homme du contrôle de la seule raison",[]],
     ["Utilise des formes d'expression de l'inconscient comme le rêve",["sym"]],
     ["Faire de l'art un acte révolutionnaire",[]]],
  w:[["Manifeste du surréalisme",1924,"Breton"],["Nadja",1928,"Breton"],["Capitale de la douleur",1926,"Eluard"]],
  q:[["Automatisme psychique pur par lequel on se propose d'exprimer […] le fonctionnement réel de la pensée.","Breton"]],
  x:[{t:1,q:"Breton : « ___ psychique pur par lequel on se propose d'exprimer […] le fonctionnement réel de la pensée »",a:"Automatisme",o:["Rêve","Mouvement","Délire"]},
     {t:1,q:"Breton : « Dictée de la pensée en l'absence de tout contrôle exercé par la ___ »",a:"raison",o:["morale","société","conscience"]},
     {t:1,al:["esthetique et morale","morale ou esthetique"],q:"Breton : « … en dehors de toute préoccupation ___ ou ___ »",a:"esthétique ou morale",o:["politique ou religieuse","sociale ou historique","logique ou scientifique"]},
     {t:1,q:"Breton : « Le surréalisme repose sur la croyance à la réalité supérieure de certaines formes d'___ négligées jusqu'à lui »",a:"associations",o:["images","émotions","écritures"]},
     {t:1,q:"Breton : « … à la toute puissance du ___, au jeu désintéressé de la ___ » (iki kelime)",a:"rêve / pensée",o:["désir / raison","hasard / parole","symbole / poésie"]},
     {t:1,al:["freud et marx","marx et freud","freudienne et marxiste","freudiennes marxistes"],q:"Quelles théories influencent le Surréalisme ? (X et Y)",a:"Freudiennes et marxistes",o:["Darwiniennes et positivistes","Cartésiennes et kantiennes","Existentialistes et chrétiennes"]}]},
 {id:"abs", n:"L'Absurde", p:"1940 – 1970",
  c:[["Illustre le désarroi de l'homme, comme étranger à un monde et à une existence dont il ne saisit plus le sens",["bar"]],
     ["Ionesco et Beckett font éclater les formes théâtrales",[]]],
  w:[["Le Roi se meurt",1962,"Ionesco"],["La Cantatrice chauve",1950,"Ionesco"],["La Leçon",1951,"Ionesco"],["Rhinocéros",1959,"Ionesco"],
     ["En attendant Godot",1953,"Beckett"],["Oh les beaux jours",1960,"Beckett"]],
  q:[],
  x:[{t:1,al:["insolite ou vacuite","insolite vacuite du monde","insolite et vacuite du monde","insolite ou vacuite du monde"],q:"Au lieu d'« absurde », Ionesco et Beckett préfèrent parler de… (iki şey)",a:"L'insolite ou la vacuité du monde",o:["Le mal du siècle","La surréalité","L'illusion romanesque"]},
     {t:1,q:"Les 2 dramaturges de l'Absurde qui font éclater les formes théâtrales ? (X et Y)",a:"Ionesco et Beckett",o:["Butor et Sarraute","Breton et Eluard","Corneille et Racine"]}]},
 {id:"nr", n:"Le Nouveau Roman", p:"Seconde moitié du XXe siècle",
  c:[["Volonté d'explorer autrement l'homme et son rapport au monde",[]],
     ["Dénoncer l'illusion romanesque en mettant fin au récit traditionnel fondé sur l'histoire et les personnages",[]]],
  w:[["La Modification",1957,"Butor"],["Le Planétarium",1959,"Sarraute"],["L'Ère du soupçon",1956,"Sarraute"]],
  q:[], x:[]}
];
const ALL_AUTH=[...new Set(MV.flatMap(m=>m.w.map(w=>w[2]).concat(m.q.map(q=>q[1]))))];
const PERIODS=[...new Set(MV.map(m=>m.p))];
const MASTER=2;
